# Generated by Django 4.2.23 on 2025-07-09 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('checklist', models.TextField(blank=True)),
                ('input_text', models.TextField(blank=True)),
                ('job_created_at', models.DateTimeField(auto_now_add=True)),
                ('job_finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-job_created_at'],
                'indexes': [models.Index(fields=['job_created_at'], name='jobs_job_job_cre_23eb9b_idx'), models.Index(fields=['job_finished_at'], name='jobs_job_job_fin_ae5740_idx'), models.Index(fields=['status', 'job_created_at'], name='jobs_job_status_672be4_idx')],
            },
        ),
    ]
